### PR TITLE
Fixes #42: Add vagrantfile

### LINKED ISSUE #42: Online demo / easy set up of example site
* Deploy a sample app to Heroku
* Provide a Vagrantfile
* Provide an example Heroku app

## app.json

```json
{
  "name": "django-watchman demo",
  "description": "Sets up a demo django app with django-watchman installed.",
  "keywords": [
    "django",
    "app",
    "monitoring"
  ],
  "website": "https://github.com/mwarkentin/django-watchman",
  "repository": "https://github.com/mwarkentin/django-watchman",
  "success_url": "/watchman",
  "env": {
    "SECRET_KEY": {
      "description": "A secret key for verifying the integrity of signed cookies.",
      "generator": "secret"
    }
  },
  "addons": [
    "heroku-postgresql",
    "openredis"
  ],
  "buildpacks": [
    {
      "url": "https://github.com/heroku/heroku-buildpack-python"
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by mwarkentin**
#42 

* Configure vagrant to set up a sample project w/ django-watchman installed
* Provisioned w/ Ansible
* Set up 2 sqlite databases
* Update .gitignore / .editorconfig

### CODE REVIEW

**Comment by justinsacbibit** [comment]
Looks good, is there any sort of "ignore" setting for landscape? To ignore the secret key warning

**Comment by mwarkentin** [comment]
@justinsacbibit Looks like it: https://docs.landscape.io/configuration.html

**Comment by mwarkentin** [comment]
@justinsacbibit Fixed!

**Comment by justinsacbibit** [comment]
Looks good to me

**Pull request merged**
