### PR TITLE
Use bytes string when writing to dummy file

### LINKED ISSUE #101: watchman.checks.storage should write bytes to test-file on Py3
Hi, i'm giving `django-minio-storage` a try and got an exception when storage-check is executed. I'm running Python 3.4.5 and Django 1.10.6. 

    Traceback (most recent call last):
      File "/Users/daniel/Workspace/my_project/lib/python3.4/site-packages/watchman/decorators.py", line 17, in wrapped
        response = func(*args, **kwargs)
      File "/Users/daniel/Workspace/my_project/lib/python3.4/site-packages/watchman/checks.py", line 63, in _check_storage
        path = default_storage.save(filename, ContentFile(content))
      File "/Users/daniel/Workspace/my_project/lib/python3.4/site-packages/django/core/files/storage.py", line 54, in save
        return self._save(name, content)
      File "/Users/daniel/Workspace/my_project/lib/python3.4/site-packages/minio_storage/storage.py", line 77, in _save
        content_type)
      File "/Users/daniel/Workspace/my_project/lib/python3.4/site-packages/minio/api.py", line 894, in put_object
        current_data, metadata=metadata)
      File "/Users/daniel/Workspace/my_project/lib/python3.4/site-packages/minio/api.py", line 1557, in _do_put_object
        raise ValueError('Input data must be bytes type')
    ValueError: Input data must be bytes type

I was able to fix it by using a `byte` instead of `str` writing to the dummy file. This should basically work on Python 2.7 - i'd file a PR later.

### PR DESCRIPTION
**Pull request by saily**
Should basically fix #101

### CODE REVIEW

**Comment by mwarkentin** [comment]
Need to do some testing with this on a Python 2.7 project before merging.

**Comment by saily** [comment]
@mwarkentin any news on this, Travis seems to be fine on py2.7

**Comment by mwarkentin** [comment]
@saily Sorry about this, fell off my radar. Just tested on one of our py2.7 apps and it looks fine. I'll get a release out shortly.

**Comment by mwarkentin** [comment]
@saily Ok, I've put 0.13.1 on pypi: https://pypi.python.org/pypi/django-watchman

Please give it a shot and let me know if it works for you or not!

**Pull request merged**
