### PR TITLE
Include assets in source tarball.

### PR DESCRIPTION
**Pull request by fladi**
It is nice to have documentation and tests in the source tarball for creating
distribution packages (e.g. for Debian).

### CODE REVIEW

**Comment by mwarkentin** [comment]
By analyzing the blame information on this pull request, we identified @none to be a potential reviewer.

**Comment by mwarkentin** [comment]
@fladi Thanks for your submission!

I have to admin I'm pretty ignorant about what goes into making distribution packages.. mainly just consume them.

Any chance you have a good link to a good summary of what goes into it? I'm also curious about your use case for this - are you wanting to package it for your own use, or looking to make it available on a public repository?

Thanks again!

**Comment by fladi** [comment]
There is a [style guide](https://wiki.debian.org/Python/LibraryStyleGuide) for Debian Python library packages which describes some of the things that should be considered when packaging a Python library.

I would package django-watchman for the official Debian repository, as I already have done this for [several other Django related packages](https://qa.debian.org/developer.php?login=fladi). The goal is to have an extensible Django stack that is maintained (in a security context) by the Debian project.

**Comment by mwarkentin** [comment]
LGTM

**Comment by mwarkentin** [comment]
@fladi I've merged this in, should be available in the next release.

**Comment by fladi** [comment]
Thanks! The Debian package should be available in the official archive a few weeks after your next release.

**Comment by mwarkentin** [comment]
Very cool - will updates be released a similar timeframe after I release a new version as well, or how does that work?

**Comment by fladi** [comment]
I will keep the package up to date as close as possible. At some point in the future it will be part of a stable release of Debian.

It works like this: I keep the django-watchman package in Debian unstable branch up to date. If there are no bugs found in the package by the Debian users it will move to Debian testing. At some point in the future the packages in testing will be *frozen* which means that no new features are accepted (read: no new upstream releases). Only bugs can be fixed. Once all critical bugs have been fixed, a new stable release of the whole Debian distribution is created (i.e. a snapshot of testing). After this, new upstream releases will be uploaded to unstable again and the cycle begins from the start (unstable -> testing -> freeze -> release). Hope this makes sense …

**Comment by mwarkentin** [comment]
Makes sense.. thanks for your work on this!

**Pull request merged**
