### PR TITLE
Check storage system

### PR DESCRIPTION
**Pull request by mwarkentin**

### CODE REVIEW

**Comment by mwarkentin** [comment]
@dlanger While you're poking around in watchman, I could use a review on this PR as well. :)

**Comment by dlanger** [comment]
In `_check_storage`, what about:

* Using a UUID filename to avoid possible concurrency issues?
* Setting the contents of the file to something including `django-watchman` to aid debugging if the files don't get cleaned up?
* Checking the return value of the size call?

Aside from that, LGTM.

**Comment by mwarkentin** [comment]
All good ideas.. will make these changes.

**Comment by mwarkentin** [comment]
@dlanger Added in #25

**Pull request merged**
