### PR TITLE
run tests on Django 2.2

### PR DESCRIPTION
**Pull request by tisdall**

### CODE REVIEW

**Comment by tisdall** [comment]
It seems PyMySQL has issues with Django 2.2 and isn't supported.

**Comment by tisdall** [comment]
If I change the 'requirements-test.txt' to use `mysqlclient>=1.3.13` it should solve the issue.  However, it seems PyMySQL was chosen for a reason (from the notes in the file).  From what I've read, it doesn't look like there's a way to get PyMySQL to work with Django 2.2 (due to it switching to using `bytes` instead of `str`).

Here's the exception on the failed check:
`django.core.exceptions.ImproperlyConfigured: mysqlclient 1.3.13 or newer is required; you have 0.9.3.`

**Comment by mwarkentin** [comment]
According to https://github.com/PyMySQL/PyMySQL/issues/790#issuecomment-533170218 this should be fixed for Django 3.0, although I wasn't able to figure out what fix he was actually referring to.

**Comment by tisdall** [comment]
Travis seems to have support for the C libraries needed for mysqlclient so I switched it over to use it and now the tests pass.  [Django 2.2 specifically says to use mysqlclient](https://docs.djangoproject.com/en/2.2/ref/databases/#mysql-db-api-drivers) and I don't think things are going to be fixed in PyMySQL to support Django 2.2 (which is a LTS version).

**Pull request merged**
