### PR TITLE
New logo for django-watchman

### PR DESCRIPTION
**Pull request by reallinfo**

### CODE REVIEW

**Comment by mwarkentin** [comment]
Looks good - any chance I can get the source files for the logo as well? A png of the vertical logo would be great. :)

**Comment by reallinfo** [comment]
Sure! i have prepared the files yet. All the files are here.

https://drive.google.com/open?id=1WWMrkOiZgUAgqFirurSMAR-YlLNbxVrP

**Comment by mwarkentin** [comment]
@reallinfo Awesome, thanks! If you wanted to include the svgs for each that'd be nice (or I can try to figure out how to generate from the AI if you want).

If you wanted another logo to do at some point, I have another repo called yuri that could be fun (named after yuri gagarin) - some cute little space man would be neat. https://github.com/mwarkentin/yuri



Do you mind if I ask why you're making these logos? Good practice, a way to contribute to these open source projects, etc? I notice you've made a bunch of issues/prs to submit logos - very cool. :)

**Comment by reallinfo** [comment]
I added the svg versions to the google driver. Utopian.io rewards open source software contributors. If you like this log you can support me using the logo i designed.(by adding it to the readme.)  Btw,  I will design a logo for yuri.

**Pull request closed without merging**
